### ISSUE TITLE
In Giant (180x94)  map, east asia need some adjustment.

### ISSUE THREAD

**Issue by 1a57danc3** [Gedemon/Civ6-YnAMP#36]
![](https://ww1.sinaimg.cn/large/6d9bd6a5gw1fb1io15qbyj211x0qstla.jpg)

Hainan island, Taiwan island, Okinawa island location adjustment.

**Comment by GuideMwit** [comment]
Thx for your suggestion ky0ncheng.

I think existing location is most appropriate and no need to modify. Based on google map, your middle circle is not an accurate location for Taiwan which is half way between Shanghai and the Philippines. Actually it is located on the islands with milk and dye. Moreover, your top circle is Kyushu island, not Okinawa which is a small island below it. 
It is also hard to place all these islands in just 7-tile-high area. I admit that their shape are quite weird due to map distortion. Noted that Japanese archipelago has been enlarged as well. So, Okinawa have to be much more South than it is in real life.
Please take a look at below picture of what I'm working with. It's hard to keep modified the code while things keep changing.

I will let Gedemon decide this issue anyway.

![01 japan korea and china](https://cloud.githubusercontent.com/assets/24505366/21467047/cb65bffa-ca11-11e6-92f1-3f19dd7bf877.jpg)
