### ISSUE TITLE
nations and create game options disapeared!

### ISSUE THREAD

**Issue by POORIANSARI** [Gedemon/Civ6-YnAMP#93]

**Comment by POORIANSARI** [comment]
i did as you said and i cant even  see any teams and options to customize!

**Comment by Gedemon** [comment]
I'd like to see the Lua.log after trying to launch the mod, TIA

**Comment by Gedemon** [comment]
Please post the modding and database logs too.

You can found all the logs here:  "..\Documents\my games\Sid Meier's Civilization VI\Logs"

**Comment by TBleader** [comment]
I have this issue, running on linux. Issue 56 isn't even an issue as I cannot start a game due to options disappearing. YnAMP seems to be the cause as when it is disabled everything is fine and I can start a game, but when it is enabled the options are gone. I can add a screenshot if you wish.
https://www.dropbox.com/s/t7g1pgdy8tg1sd4/Database.log?dl=0
https://www.dropbox.com/s/fbhflweew2ym8gk/Lua.log?dl=0
https://www.dropbox.com/s/3n876uq01c7tcji/Modding.log?dl=0

**Comment by POORIANSARI** [comment]
The game version and the mod version must be rechecked. I solved the problem by downgrading the game to 3.03 and then installing the mod.
